# Generated by Django 2.2 on 2019-10-11 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='played',
        ),
    ]
