# Generated by Django 2.2 on 2019-04-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
