# Generated by Django 2.2 on 2019-12-25 03:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_remove_schedule_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='match_type',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
