# Generated by Django 2.2 on 2019-04-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_dblog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='second_start',
        ),
        migrations.AddField(
            model_name='team',
            name='second_start_l',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='second_start_r',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='first_start',
            field=models.BooleanField(default=True),
        ),
    ]
