# Generated by Django 2.2 on 2019-04-26 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_auto_20190426_0312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DbLog',
        ),
        migrations.DeleteModel(
            name='Error',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
