# Generated by Django 2.2 on 2019-05-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0006_match'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='second_start_l',
            new_name='second_start_left',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='second_start_r',
            new_name='second_start_right',
        ),
    ]
