# Generated by Django 2.2 on 2019-05-11 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0007_auto_20190511_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='first_climb',
        ),
        migrations.RemoveField(
            model_name='match',
            name='second_climb',
        ),
        migrations.RemoveField(
            model_name='match',
            name='third_climb',
        ),
        migrations.AddField(
            model_name='match',
            name='auto_cargo',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='match',
            name='auto_hatch',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='match',
            name='climb',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='team',
            name='auto_cargo',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='team',
            name='auto_hatch',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='cargo_hatch',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='first_cargo',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='first_hatch',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='match',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(255), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='name',
            field=models.CharField(default='unnamed_team', max_length=40),
        ),
        migrations.AlterField(
            model_name='match',
            name='number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9000), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='second_cargo',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='second_hatch',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='ship_cargo',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='third_cargo',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='third_hatch',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
    ]
