# Generated by Django 2.2 on 2019-05-11 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0008_auto_20190511_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='second_start_l',
            new_name='second_start_left',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='second_start_r',
            new_name='second_start_right',
        ),
        migrations.RemoveField(
            model_name='match',
            name='first_start',
        ),
        migrations.RemoveField(
            model_name='team',
            name='first_start',
        ),
    ]
