# Generated by Django 2.2 on 2019-05-12 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0010_auto_20190511_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='cargo_hatch',
            new_name='ship_hatch',
        ),
    ]
