# Generated by Django 2.2 on 2019-05-12 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0011_auto_20190512_0211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='name',
            new_name='team_name',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='number',
            new_name='team_number',
        ),
    ]
