# Generated by Django 2.2 on 2019-05-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0013_auto_20190513_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='NA')),
                ('TBA_key', models.TextField(default='NA')),
                ('TBA_id', models.TextField(default='NA')),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_name',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_number',
        ),
        migrations.RemoveField(
            model_name='team',
            name='auto_cargo',
        ),
        migrations.RemoveField(
            model_name='team',
            name='auto_hatch',
        ),
        migrations.RemoveField(
            model_name='team',
            name='defense_matches',
        ),
        migrations.RemoveField(
            model_name='team',
            name='defense_time',
        ),
        migrations.RemoveField(
            model_name='team',
            name='first_cargo',
        ),
        migrations.RemoveField(
            model_name='team',
            name='first_climb',
        ),
        migrations.RemoveField(
            model_name='team',
            name='first_hatch',
        ),
        migrations.RemoveField(
            model_name='team',
            name='first_start',
        ),
        migrations.RemoveField(
            model_name='team',
            name='matches',
        ),
        migrations.RemoveField(
            model_name='team',
            name='second_cargo',
        ),
        migrations.RemoveField(
            model_name='team',
            name='second_climb',
        ),
        migrations.RemoveField(
            model_name='team',
            name='second_hatch',
        ),
        migrations.RemoveField(
            model_name='team',
            name='second_start',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ship_cargo',
        ),
        migrations.RemoveField(
            model_name='team',
            name='ship_hatch',
        ),
        migrations.RemoveField(
            model_name='team',
            name='third_cargo',
        ),
        migrations.RemoveField(
            model_name='team',
            name='third_climb',
        ),
        migrations.RemoveField(
            model_name='team',
            name='third_hatch',
        ),
    ]
