# Generated by Django 2.2 on 2019-05-22 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0015_team_event_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='event',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='entry.Event'),
        ),
        migrations.AddField(
            model_name='match',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='entry.Team'),
        ),
    ]
