# Generated by Django 2.2 on 2019-05-23 00:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0016_auto_20190522_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='TBA_eventType',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
