# Generated by Django 2.2 on 2019-05-25 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0017_event_tba_eventtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='event_four',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entry.Event'),
        ),
        migrations.AddField(
            model_name='team',
            name='event_three',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entry.Event'),
        ),
        migrations.AddField(
            model_name='team',
            name='event_two',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entry.Event'),
        ),
        migrations.AlterField(
            model_name='team',
            name='event_one',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entry.Event'),
        ),
    ]
