# Generated by Django 2.2 on 2019-05-25 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0018_auto_20190525_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='cur_event',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)]),
        ),
    ]
