# Generated by Django 2.2 on 2019-05-25 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0019_team_cur_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='cur_event',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='entry.Event'),
        ),
    ]
