# Generated by Django 2.2 on 2019-05-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0020_auto_20190525_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='TBA_key',
            field=models.CharField(default='NA', max_length=40),
        ),
    ]
