# Generated by Django 2.2 on 2019-05-26 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0021_team_tba_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='TBA_id',
        ),
    ]
