# Generated by Django 2.2.1 on 2019-05-28 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0023_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.DateField(default=datetime.date(9999, 12, 31)),
        ),
    ]
