# Generated by Django 2.2.1 on 2019-05-28 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0024_event_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default=datetime.date(9999, 12, 31)),
        ),
    ]
