# Generated by Django 2.2.1 on 2019-05-28 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0025_auto_20190528_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='blue_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='schedule',
            name='red_score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)]),
        ),
    ]
