# Generated by Django 2.2.1 on 2019-05-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0026_auto_20190528_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='played',
            field=models.BooleanField(default=False),
        ),
    ]
