# Generated by Django 2.2 on 2019-05-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0028_remove_event_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.TextField(default=99999999),
        ),
    ]
