# Generated by Django 2.2 on 2019-05-31 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0031_auto_20190529_0155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='cur_event',
            new_name='event_five',
        ),
    ]
