# Generated by Django 2.2 on 2019-05-31 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0032_auto_20190531_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='imported',
            field=models.BooleanField(default=False),
        ),
    ]
