# Generated by Django 2.2 on 2019-06-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0033_event_imported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='team', max_length=100),
        ),
    ]
