# Generated by Django 2.2 on 2019-06-07 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0034_auto_20190601_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='TBA_key',
        ),
        migrations.RemoveField(
            model_name='team',
            name='event_five',
        ),
        migrations.RemoveField(
            model_name='team',
            name='event_four',
        ),
        migrations.RemoveField(
            model_name='team',
            name='event_one',
        ),
        migrations.RemoveField(
            model_name='team',
            name='event_three',
        ),
        migrations.RemoveField(
            model_name='team',
            name='event_two',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
    ]
