# Generated by Django 2.2 on 2019-06-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0035_auto_20190607_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='team', max_length=100),
        ),
    ]
