# Generated by Django 2.2 on 2019-06-07 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0036_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='TBA_key',
            field=models.TextField(default='NA', max_length=40),
        ),
        migrations.AddField(
            model_name='team',
            name='event_five',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entry.Event'),
        ),
        migrations.AddField(
            model_name='team',
            name='event_four',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entry.Event'),
        ),
        migrations.AddField(
            model_name='team',
            name='event_one',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='entry.Event'),
        ),
        migrations.AddField(
            model_name='team',
            name='event_three',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entry.Event'),
        ),
        migrations.AddField(
            model_name='team',
            name='event_two',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entry.Event'),
        ),
    ]
