# Generated by Django 2.2 on 2019-06-07 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0037_auto_20190607_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='TBA_key',
        ),
    ]
