# Generated by Django 2.2 on 2019-06-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0038_remove_team_tba_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='TBA_key',
            field=models.TextField(default='NA', max_length=40),
        ),
    ]
