# Generated by Django 2.2 on 2019-06-07 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0039_team_tba_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='event_five',
        ),
    ]
