# Generated by Django 2.2 on 2019-06-07 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0040_remove_team_event_five'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='event_five',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entry.Event'),
        ),
    ]
