# Generated by Django 4.0.1 on 2022-01-23 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0002_log_completeddate_log_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hours.mentor'),
        ),
    ]
