# Generated by Django 4.0.6 on 2022-08-10 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0004_remove_log_completeddate_remove_log_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='duration',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)]),
        ),
        migrations.AddField(
            model_name='log',
            name='out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='log',
            name='total',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
