# Generated by Django 4.0.6 on 2022-08-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0005_log_duration_log_out_log_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
