# Generated by Django 4.0.6 on 2022-08-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0006_alter_log_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
