# Generated by Django 4.1.7 on 2023-12-02 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_alter_orgmember_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='settings',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, to='organizations.orgsettings'),
        ),
        migrations.AlterField(
            model_name='orgmember',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='orgmember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
