# Generated by Django 3.0.2 on 2020-02-01 19:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='TBA_eventType',
            new_name='FIRST_eventType',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='TBA_key',
            new_name='FIRST_key',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='TBA_key',
            new_name='FIRST_key',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='TBA_key',
            new_name='FIRST_key',
        ),
        migrations.AddField(
            model_name='match',
            name='balls_collected',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='match',
            name='baseline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='defense_fouls',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='match',
            name='defense_rating',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='match',
            name='fouls',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='match',
            name='fouls_auto',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='match',
            name='full_cycles',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='match',
            name='inner',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='match',
            name='inner_auto',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='match',
            name='low',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='match',
            name='low_auto',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='match',
            name='outer',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='match',
            name='outer_auto',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='match',
            name='rating_auto',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='match',
            name='wheel_rating',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='team',
            name='event_five',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entry.Event'),
        ),
        migrations.AlterField(
            model_name='match',
            name='defense_time',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(135000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
