# Generated by Django 2.2 on 2019-12-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='comments',
            field=models.TextField(default=''),
        ),
    ]
