# Generated by Django 2.2 on 2020-03-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.ImageField(default='/robots/default.jpg', null=True, upload_to='robots'),
        ),
        migrations.AddField(
            model_name='images',
            name='name',
            field=models.CharField(default='Wally', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='images',
            field=models.ManyToManyField(to='entry.Images'),
        ),
    ]
