# Generated by Django 4.0.1 on 2022-01-10 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_match_team_ownership_pits_team_ownership_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='climb_location',
            new_name='endgame_action',
        ),
        migrations.RemoveField(
            model_name='match',
            name='auto_route',
        ),
        migrations.RemoveField(
            model_name='match',
            name='auto_start',
        ),
        migrations.RemoveField(
            model_name='match',
            name='cycle_style',
        ),
        migrations.RemoveField(
            model_name='match',
            name='defended_by',
        ),
        migrations.RemoveField(
            model_name='match',
            name='field_timeout_pos',
        ),
        migrations.RemoveField(
            model_name='match',
            name='inner',
        ),
        migrations.RemoveField(
            model_name='match',
            name='inner_auto',
        ),
        migrations.RemoveField(
            model_name='match',
            name='missed_balls_auto',
        ),
        migrations.RemoveField(
            model_name='match',
            name='outer',
        ),
        migrations.RemoveField(
            model_name='match',
            name='outer_auto',
        ),
        migrations.RemoveField(
            model_name='match',
            name='preloaded_balls',
        ),
        migrations.RemoveField(
            model_name='match',
            name='rating_auto',
        ),
        migrations.RemoveField(
            model_name='match',
            name='wheel_rating',
        ),
        migrations.RemoveField(
            model_name='match',
            name='wheel_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='yellow_card_descrip',
        ),
        migrations.RemoveField(
            model_name='pits',
            name='climb_balance',
        ),
        migrations.RemoveField(
            model_name='pits',
            name='climb_buddy',
        ),
        migrations.RemoveField(
            model_name='pits',
            name='wheel_manipulator',
        ),
        migrations.AddField(
            model_name='match',
            name='climb_attempts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='climb_comments',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='match',
            name='climb_timer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='defense_timer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='upper',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='match',
            name='upper_auto',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='match',
            name='yellow_card_description',
            field=models.TextField(default=''),
        ),
    ]
