# Generated by Django 2.2 on 2020-03-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_auto_20200325_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(default='/robots/default.jpg', upload_to='robots'),
        ),
    ]
