# Generated by Django 2.2 on 2019-12-28 20:12

import apps.entry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_match_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='blue1',
            field=models.IntegerField(default=0, verbose_name=apps.entry.models.Team),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='blue2',
            field=models.IntegerField(default=0, verbose_name=apps.entry.models.Team),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='blue3',
            field=models.IntegerField(default=0, verbose_name=apps.entry.models.Team),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='red1',
            field=models.IntegerField(default=0, verbose_name=apps.entry.models.Team),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='red2',
            field=models.IntegerField(default=0, verbose_name=apps.entry.models.Team),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='red3',
            field=models.IntegerField(default=0, verbose_name=apps.entry.models.Team),
        ),
    ]
