# Generated by Django 4.0.8 on 2023-02-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_match_auto_cones_match_auto_cubes_match_cones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='lock_status',
        ),
    ]
