# Generated by Django 2.2.13 on 2021-08-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_auto_20210825_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='reg_id',
            field=models.CharField(default='team', max_length=100),
        ),
    ]
