# Generated by Django 2.2 on 2020-02-02 00:17

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_auto_20200201_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='test',
            field=models.DateField(default=datetime.date(2020, 1, 1), validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 12, 31)), django.core.validators.MinValueValidator(datetime.date(2020, 1, 1))]),
        ),
        migrations.CreateModel(
            name='Pits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(default='NA')),
                ('event', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='entry.Event')),
                ('team', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='entry.Team')),
            ],
        ),
    ]
