# Generated by Django 4.0.8 on 2023-02-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_remove_match_lock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='avatar',
            field=models.CharField(default='NA', max_length=10000),
        ),
    ]
