# Generated by Django 2.2 on 2020-02-02 00:46

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_auto_20200202_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='comments',
            new_name='game_comments',
        ),
        migrations.RemoveField(
            model_name='event',
            name='test',
        ),
        migrations.AddField(
            model_name='match',
            name='auto_start',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='match',
            name='climb_attempts',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='match',
            name='climb_location',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(-100)]),
        ),
        migrations.AddField(
            model_name='match',
            name='climb_time',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(55000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='match',
            name='initial_comments',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='match',
            name='on_field',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='match',
            name='preloaded_balls',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='pits',
            name='comments',
            field=models.TextField(default='No Comments'),
        ),
        migrations.AddField(
            model_name='pits',
            name='images',
            field=models.TextField(default='No Images Yet'),
        ),
        migrations.AddField(
            model_name='pits',
            name='motor_number',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='pits',
            name='motor_type',
            field=models.CharField(choices=[('none', "Doesn't Drive?"), ('cim', 'CIM Motors'), ('falcon', 'Falcon 500 Motors'), ('neo', 'NEO Motors'), ('other', 'Unusual DriveTrain... See Comments')], default='none', max_length=6),
        ),
        migrations.AddField(
            model_name='pits',
            name='weight',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateField(default=datetime.date(2020, 1, 1), validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 12, 31)), django.core.validators.MinValueValidator(datetime.date(2020, 1, 1))]),
        ),
        migrations.AlterField(
            model_name='match',
            name='balls_collected',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='full_cycles',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='inner',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='inner_auto',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='low',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='low_auto',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='outer',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='outer_auto',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
