# Generated by Django 4.0.9 on 2023-02-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_remove_match_lock_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='auto_placement',
            field=models.TextField(default='000000000000000000000000000000000000', max_length=36),
        ),
        migrations.AlterField(
            model_name='match',
            name='placement',
            field=models.TextField(default='000000000000000000000000000000000000', max_length=36),
        ),
    ]
