# Generated by Django 2.2 on 2019-12-28 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_auto_20191228_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='first_start',
        ),
        migrations.RemoveField(
            model_name='match',
            name='second_start',
        ),
        migrations.AddField(
            model_name='match',
            name='start',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)]),
        ),
    ]
