# Generated by Django 4.0.1 on 2022-01-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_rename_climb_location_match_endgame_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='glance',
            field=models.FileField(blank=True, null=True, upload_to='json/'),
        ),
    ]
