# Generated by Django 2.2 on 2020-03-26 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_auto_20200325_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='event',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='entry.Event'),
        ),
    ]
