# Generated by Django 2.2 on 2020-02-02 00:47

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_auto_20200202_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.DateField(default=datetime.date(2020, 1, 1), validators=[django.core.validators.MaxValueValidator(datetime.date(2020, 12, 31)), django.core.validators.MinValueValidator(datetime.date(2020, 1, 1))]),
        ),
    ]
