# Generated by Django 2.2.13 on 2021-08-25 18:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_auto_20210825_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='reg_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
