# Generated by Django 4.0.1 on 2022-01-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0005_alter_event_options_alter_images_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='FIRST_eventType',
            field=models.TextField(default='NA'),
        ),
    ]
