# Generated by Django 2.2 on 2020-02-02 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0005_event_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='FIRST_key',
        ),
    ]
