# Generated by Django 4.0.1 on 2022-01-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0006_alter_event_first_eventtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='teams',
            field=models.JSONField(default='{"teams": []}', null=True),
        ),
    ]
