# Generated by Django 2.2.13 on 2021-08-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0006_team_glance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='glance',
        ),
    ]
