# Generated by Django 2.2 on 2020-03-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0006_remove_team_first_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='match_type',
            field=models.TextField(default='NA', max_length=40),
        ),
    ]
