# Generated by Django 4.0.1 on 2022-01-12 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0007_event_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='teams',
        ),
    ]
