# Generated by Django 2.2.13 on 2021-08-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0007_remove_team_glance'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='glance',
            field=models.FileField(null=True, upload_to='json/'),
        ),
    ]
