# Generated by Django 2.2 on 2020-03-23 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0007_auto_20200322_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='FIRST_key',
        ),
    ]
