# Generated by Django 4.0.1 on 2022-01-16 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0008_remove_event_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamsettings',
            old_name='allowPhotos',
            new_name='allow_photos',
        ),
        migrations.RenameField(
            model_name='teamsettings',
            old_name='allowSchedule',
            new_name='allow_schedule',
        ),
        migrations.RenameField(
            model_name='teamsettings',
            old_name='currentEvent',
            new_name='current_event',
        ),
        migrations.RenameField(
            model_name='teamsettings',
            old_name='newUserCreation',
            new_name='new_user_creation',
        ),
        migrations.RenameField(
            model_name='teamsettings',
            old_name='newUserPosition',
            new_name='new_user_position',
        ),
    ]
