# Generated by Django 2.2 on 2020-03-23 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0008_remove_schedule_first_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='low',
            new_name='lower',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='low_auto',
            new_name='lower_auto',
        ),
        migrations.RemoveField(
            model_name='team',
            name='event_five',
        ),
        migrations.RemoveField(
            model_name='team',
            name='event_four',
        ),
        migrations.RemoveField(
            model_name='team',
            name='event_one',
        ),
        migrations.RemoveField(
            model_name='team',
            name='event_three',
        ),
        migrations.RemoveField(
            model_name='team',
            name='event_two',
        ),
    ]
