# Generated by Django 2.2 on 2020-04-30 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0009_auto_20200430_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pits',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='pits',
            name='motor_number',
        ),
        migrations.RemoveField(
            model_name='pits',
            name='motor_type',
        ),
        migrations.AddField(
            model_name='pits',
            name='auto_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pits',
            name='auto_route',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pits',
            name='auto_scoring',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='pits',
            name='ball_capacity',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='pits',
            name='ball_intake',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pits',
            name='climb_balance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pits',
            name='climb_buddy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pits',
            name='climb_locations',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='pits',
            name='drivetrain_motorquantity',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='pits',
            name='drivetrain_motortype',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pits',
            name='drivetrain_style',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pits',
            name='drivetrain_wheels',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pits',
            name='low_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pits',
            name='scouter_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pits',
            name='shooter_style',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pits',
            name='tele_positions',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='pits',
            name='tele_scoring',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='pits',
            name='wheel_manipulator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pits',
            name='weight',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(0)]),
        ),
    ]
