# Generated by Django 4.0.1 on 2022-01-29 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0009_rename_allowphotos_teamsettings_allow_photos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='fouls_auto',
            new_name='auto_fouls',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='climb_timer',
            new_name='climb_time',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='defense_timer',
            new_name='defense_time',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='dt_fouls',
            new_name='fouls_driver',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='hp_fouls',
            new_name='fouls_hp',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='ball_intake_type',
            new_name='intake_type',
        ),
        migrations.RemoveField(
            model_name='match',
            name='climbed',
        ),
        migrations.RemoveField(
            model_name='match',
            name='fouls',
        ),
        migrations.RemoveField(
            model_name='match',
            name='played_defense',
        ),
        migrations.AddField(
            model_name='match',
            name='auto_route',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='match',
            name='defended_by',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='lock_status',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='match',
            name='missed_auto',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='match',
            name='offensive_fouls',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='match',
            name='preloaded_balls',
            field=models.BooleanField(default=True),
        ),
    ]
