# Generated by Django 2.2 on 2020-03-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0009_auto_20200323_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='robot',
            field=models.ImageField(default='/robots/default.jpg', upload_to='robots'),
        ),
    ]
