# Generated by Django 2.2 on 2020-04-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0010_auto_20200430_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_defended',
            field=models.TextField(default=''),
        ),
    ]
