# Generated by Django 2.2 on 2020-03-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0010_team_robot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='robot',
            field=models.ImageField(default='/robots/default.jpg', null=True, upload_to='robots'),
        ),
    ]
