# Generated by Django 4.0.1 on 2022-01-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0010_rename_fouls_auto_match_auto_fouls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='climb_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
