# Generated by Django 2.2 on 2020-04-30 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0011_auto_20200430_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pits',
            name='number',
        ),
    ]
