# Generated by Django 4.0.1 on 2022-01-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0011_alter_match_climb_attempts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='missed_auto',
            new_name='missed_balls_auto',
        ),
    ]
