# Generated by Django 4.0.1 on 2022-02-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0012_rename_missed_auto_match_missed_balls_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(choices=[('PA', 'Public Access'), ('NA', 'No Access'), ('OV', 'Only View'), ('MS', 'Match Scout'), ('GS', 'General Scout'), ('PS', 'Pit Scout'), ('DT', 'Drive Team'), ('LS', 'Lead Scout')], default='GS', max_length=2),
        ),
        migrations.AlterField(
            model_name='teamsettings',
            name='new_user_position',
            field=models.CharField(choices=[('PA', 'Public Access'), ('NA', 'No Access'), ('OV', 'Only View'), ('MS', 'Match Scout'), ('GS', 'General Scout'), ('PS', 'Pit Scout'), ('DT', 'Drive Team')], default='OV', max_length=2),
        ),
    ]
