# Generated by Django 2.2 on 2020-05-02 19:49

import apps.entry.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0012_remove_pits_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='climb',
        ),
        migrations.AddField(
            model_name='match',
            name='cycle_style',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='match',
            name='defended_by',
            field=models.IntegerField(default=0, verbose_name=apps.entry.models.Team),
        ),
        migrations.AddField(
            model_name='match',
            name='played_defense',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_defended',
            field=models.IntegerField(default=0, verbose_name=apps.entry.models.Team),
        ),
    ]
