# Generated by Django 2.2 on 2020-05-02 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0013_auto_20200502_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='full_cycles',
        ),
    ]
