# Generated by Django 4.0.2 on 2022-02-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0016_match_auto_start_x_match_auto_start_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='original',
            field=models.BooleanField(default=True),
        ),
    ]
