# Generated by Django 2.2 on 2020-05-02 20:10

import apps.entry.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0016_match_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='defended_by',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(-1)], verbose_name=apps.entry.models.Team),
        ),
    ]
