# Generated by Django 4.0.2 on 2022-02-19 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0017_images_original'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='original',
        ),
    ]
