# Generated by Django 2.2 on 2020-05-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0017_auto_20200502_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='climbed',
            field=models.BooleanField(default=False),
        ),
    ]
