# Generated by Django 2.2 on 2020-05-16 01:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0018_match_climbed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='defended_by',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(-1)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_defended',
            field=models.IntegerField(default=0),
        ),
    ]
