# Generated by Django 4.0.2 on 2022-03-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0018_remove_images_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='description',
            field=models.TextField(default='NA', max_length=100),
        ),
    ]
