# Generated by Django 2.2 on 2020-05-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0019_auto_20200515_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
