# Generated by Django 4.0.2 on 2022-03-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0020_alter_teammember_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='gouda',
            field=models.FloatField(default=0),
        ),
    ]
