# Generated by Django 2.2 on 2020-05-22 20:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0020_match_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='missed_balls_auto',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
