# Generated by Django 2.2 on 2020-05-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0021_match_missed_balls_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='yellow_card_descrip',
            field=models.TextField(default=''),
        ),
    ]
