# Generated by Django 4.0.2 on 2022-03-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0021_match_gouda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='gouda',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
