# Generated by Django 4.0.6 on 2022-08-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0022_alter_match_gouda'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
