# Generated by Django 2.2 on 2020-06-09 20:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0022_match_yellow_card_descrip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='defended_by',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
