# Generated by Django 4.0.6 on 2022-12-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0023_schedule_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='balls_collected',
        ),
        migrations.AlterField(
            model_name='match',
            name='defended_by',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_defended',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
