# Generated by Django 2.2.13 on 2020-06-14 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0024_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='entry.Team'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(choices=[('NA', 'No Access'), ('OV', 'Only View'), ('MS', 'Match Scout'), ('PS', 'Pit Scout'), ('GS', 'General Scout'), ('LS', 'Lead Scout'), ('DT', 'Drive Team')], default='GS', max_length=2),
        ),
    ]
