# Generated by Django 2.2.13 on 2020-06-14 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0025_auto_20200613_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(default=4343, on_delete=django.db.models.deletion.CASCADE, to='entry.Team'),
        ),
    ]
