# Generated by Django 4.0.6 on 2022-12-26 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0026_alter_orgsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgmember',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entry.organization'),
        ),
    ]
