# Generated by Django 4.0.6 on 2022-12-26 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0027_orgmember_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='ownership',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entry.organization'),
        ),
        migrations.AlterField(
            model_name='pits',
            name='ownership',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entry.organization'),
        ),
    ]
