# Generated by Django 4.0.6 on 2022-12-26 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0028_alter_match_ownership_alter_pits_ownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entry.team'),
        ),
    ]
