# Generated by Django 2.2.13 on 2020-06-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0028_auto_20200614_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(choices=[('NA', 'No Access'), ('OV', 'Only View'), ('MS', 'Match Scout'), ('GS', 'General Scout'), ('PS', 'Pit Scout'), ('DT', 'Drive Team'), ('LS', 'Lead Scout')], default='GS', max_length=2),
        ),
    ]
