# Generated by Django 2.2.13 on 2020-06-17 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0029_auto_20200614_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='pits',
            name='drivetrain_speed',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='pits',
            name='drivetrain_transmission',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pits',
            name='targeting_system',
            field=models.TextField(default=''),
        ),
    ]
