# Generated by Django 2.2 on 2020-07-09 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0030_auto_20200616_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team_ownership',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entry.Team'),
        ),
    ]
