# Generated by Django 2.2 on 2020-07-09 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0031_match_team_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='pits',
            name='team_ownership',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entry.Team'),
        ),
    ]
