# Generated by Django 4.0.2 on 2023-01-06 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0032_rename_blue_gouda_result_gouda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='gouda',
        ),
    ]
