# Generated by Django 4.0.8 on 2023-01-10 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0032_rename_blue_gouda_result_gouda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='gouda',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='entry.team'),
        ),
    ]
