# Generated by Django 2.2.13 on 2020-07-20 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0032_pits_team_ownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowPhotos', models.BooleanField(default=True)),
                ('allowSchedule', models.BooleanField(default=True)),
                ('newUserCreation', models.CharField(choices=[('MA', 'Manual Approval, Open Registration'), ('MM', 'Manual Creation of All Users'), ('AA', 'Open Registration and Use')], default='MM', max_length=2)),
                ('newUserPosition', models.CharField(choices=[('NA', 'No Access'), ('OV', 'Only View'), ('MS', 'Match Scout'), ('GS', 'General Scout'), ('PS', 'Pit Scout'), ('DT', 'Drive Team')], default='OV', max_length=2)),
                ('team', models.ForeignKey(default=4346, on_delete=django.db.models.deletion.CASCADE, to='entry.Team')),
            ],
        ),
    ]
