# Generated by Django 4.0.2 on 2023-01-11 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0033_remove_match_gouda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='entry.team'),
        ),
    ]
