# Generated by Django 2.2.13 on 2021-01-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0033_teamsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='tutorial_completed',
            field=models.BooleanField(default=False),
        ),
    ]
