# Generated by Django 2.2.13 on 2021-05-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0034_teammember_tutorial_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='pick_status',
            field=models.IntegerField(default=0),
        ),
    ]
