# Generated by Django 2.2.13 on 2021-02-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0035_auto_20210214_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='pick_status',
            field=models.IntegerField(null=True),
        ),
    ]
