# Generated by Django 2.2.13 on 2021-02-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0036_team_pick_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='pick_status',
            field=models.IntegerField(default=0),
        ),
    ]
