# Generated by Django 2.2.13 on 2021-05-18 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0035_auto_20210127_1056'),
        ('entry', '0038_auto_20210214_1546'),
    ]

    operations = [
    ]
