# Generated by Django 2.2.13 on 2021-05-18 10:45

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0039_merge_20210518_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateField(default=datetime.date(2020, 1, 1), validators=[django.core.validators.MaxValueValidator(datetime.date(2220, 12, 31)), django.core.validators.MinValueValidator(datetime.date(2020, 1, 1))]),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateField(default=datetime.date(2020, 1, 1), validators=[django.core.validators.MaxValueValidator(datetime.date(2220, 12, 31)), django.core.validators.MinValueValidator(datetime.date(2020, 1, 1))]),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_ownership',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entry.Team'),
        ),
        migrations.AlterField(
            model_name='pits',
            name='team_ownership',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='entry.Team'),
        ),
    ]
