# Generated by Django 2.2.13 on 2021-05-18 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0041_auto_20210518_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='pick_status',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)]),
        ),
    ]
