# Generated by Django 2.2.13 on 2021-05-19 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0042_auto_20210518_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='placeholder',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(default=4491, on_delete=django.db.models.deletion.CASCADE, to='entry.Team'),
        ),
        migrations.AlterField(
            model_name='teamsettings',
            name='team',
            field=models.ForeignKey(default=4491, on_delete=django.db.models.deletion.CASCADE, to='entry.Team'),
        ),
    ]
