# Generated by Django 2.2.13 on 2021-05-20 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0043_auto_20210519_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsettings',
            name='currentEvent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='entry.Event'),
        ),
    ]
