# Generated by Django 2.2.13 on 2021-05-20 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0044_teamsettings_currentevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(default=4346, on_delete=django.db.models.deletion.CASCADE, to='entry.Team'),
        ),
        migrations.AlterField(
            model_name='teamsettings',
            name='team',
            field=models.ForeignKey(default=4346, on_delete=django.db.models.deletion.CASCADE, to='entry.Team'),
        ),
    ]
